name: Test pipeline
on:
  pull_request:
    branches: 
      - test_ci
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: pip install -r test_requirements.txt

      - name: Run test
        run: pytest --cov=pycpfcnpj tests/*.py

